spring.application.name=session13
server.port=1213

spring.datasource.url=jdbc:postgresql://localhost:5432/session13
spring.datasource.username=postgres
spring.datasource.password=Manhcuong281207@

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true