spring.application.name=session10

server.port = 1210

spring.datasource.url=jdbc:postgresql://localhost:5432/session10
spring.datasource.username=postgres
spring.datasource.password=Manhcuong281207@

spring.jpa.database=POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# --- CẤU HÌNH LOGGING (BỔ SUNG) ---
# Cấu hình mức độ log (OFF, ERROR, WARN, INFO, DEBUG, TRACE)
logging.level.root=INFO
logging.level.com.example.session10=DEBUG

# Đường dẫn và tên file log sẽ được lưu
logging.file.name=logs/app.log

# Định dạng ngày giờ trong log file
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.max-history=30